### ISSUE TITLE
Write combined styles to separate files

### ISSUE THREAD

**Issue by thasmo** [konitter/gulp-combine-media-queries#2]
Is it possible to write combined styles for each media query to a separate file?
If not, that would be a handy feature I guess - what do you think?

**Comment by konitter** [comment]
It is sufficient to combine the CSS file using the `gulp-concat` prior to combining the style.
https://github.com/wearefractal/gulp-concat

```
var concat = require('gulp-concat');
var cmq = require('gulp-combine-media-queries');

gulp.task('cmq', function () {
  gulp.src('src/**/*.css')
    .pipe(concat('all.css'))
    .pipe(cmq())
    .pipe(gulp.dest('dist'));
});
```

How's this?

**Comment by khusseini** [comment]
I think this is the exact opposite of what thasmo was asking. I am also looking for a way to take out all media queries and put them into a separate file.

**Comment by thasmo** [comment]
Exactly, I'd like to put definitions for media queries into separate files.

**Comment by khusseini** [comment]
I got it to work in my fork. Maybe could use some minor work, like configurable filename, but at least it is there now.
Check it out https://github.com/konitter/gulp-combine-media-queries/pull/4

**Comment by MaikelGG** [comment]
Hey, you mentioned the script should work with the @mozzymoz mentioned fork , but I can't get it to work with generating separate files.
https://github.com/greenpeace/ggw_styleguide/blob/develop/gulpfile.js

Is it merged code tested with this function or are my settings not good?

**Comment by khusseini** [comment]
Are there any errors coming up on your end? The settings you set should be
alright.

**Comment by MaikelGG** [comment]
It seems that running 'npm install gulp-combine-media-queries --save-dev' didn't fetch the latest code, so I have overwritten it with the version of june 19, and now it works :)

**Comment by khusseini** [comment]
Wonderful

**Comment by konitter** [comment]
Hi, @mozzymoz @MaikelGG .
I have just published to npm now.

https://www.npmjs.org/package/gulp-combine-media-queries
