### ISSUE TITLE
Bug with url @import

### ISSUE THREAD

**Issue by DarkPreacher** [konitter/gulp-combine-media-queries#3]
Hi!
There is a bug with @imports.
Example file `style.less`:

``` css
@import url(http://fonts.googleapis.com/css?family=Titillium+Web:600);
```

and nothing happens, output is empty.

Gulp task I'm using:

``` javascript
gulp.task('style', function () {
    gulp.src(source.css + '/style.less')
        .pipe(less({ sourceMap: true }))
            .on('error', gutil.log)
            .pipe(gulp.dest(assets.css))
            .pipe(browserSync.reload({ stream: true }))
        .pipe(rename({ suffix: '.min' }))
        .pipe(less())
            .on('error', gutil.log)
        .pipe(cmq())
        .pipe(csso())
            .pipe(gulp.dest(assets.css))
});
```

In `style.css` @imports exists, but in `style.min.css` @imports ripped out.
If I comment `.pipe(cmq())` — @imports comes back.

**Comment by 4rn0** [comment]
I have the same problem.
Any chance of fixing this?

**Comment by didoo** [comment]
Same for me. @konitter if you look at the Grunt version (https://github.com/JohnCashmore/grunt-combine-media-queries/blob/master/tasks/combine-media-queries.js) you are missing these:

```
// Process media queries
var processImportURL = function(importURL) {
var strCss = '';
strCss += '@import ' + importURL.import + ';';
return strCss;
};

// Function to import URL
var outputImportURL = function(importURL){
importURL.forEach(function(item){
strStyles += processImportURL(item);
});
};

// Check if import URL was processed
if (processedCSS.importURL.length !== 0){
outputImportURL(processedCSS.importURL);
}
```

Do you think is something you can fix?

**Comment by geibi** [comment]
copy that. it would be really nice if you could apply the fix

**Comment by didoo** [comment]
@konitter it would help if I prepare a fix it, and then do a pull request? would you merge my changes in the master branch then? I am absolutely not an expert of Gulp plugins, and it would take me some time, but if this could solve the problem...

**Comment by garand** [comment]
Same problem here. Looking forward to a fix. :+1:

**Comment by geibi** [comment]
thanks for the merge. everything seems good now :)
